debug: true
logging:
    level:
        org:
            springframework: INFO
management:
    shell:
        auth:
            simple:
                user:
                    name: user
                    password: 123
            type: simple
#            test
        ssh:
            port: 8099
server:
    error:
        whitelabel:
            enabled: false
    port: 8090
spring:
    data:
        rest:
            basePath: /api
    datasource:
        data: classpath:db/data.sql
        driver-class-name: org.h2.Driver
        password: 123456
        schema: classpath:db/schema.sql
        url: jdbc:h2:file:~/.h2/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
        username: root
    h2:
        console:
            enabled: true
    output:
        ansi:
            enabled: always
    thymeleaf:
        cache: false
        check-template-location: true
        content-type: text/html
        encoding: UTF-8
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    rabbitmq:
        host: 116.196.75.86
        port: 5672
        username: myuser
        password: mypass
        virtual-host: /
    redis:
      host: localhost
      port: 6379

#        logging.level.org.springframework.amqp=ERROR
#        logging.level.com.patterncat=INFO
